version: "3"
services:
  mongodb:
    image: mongo
    container_name: "atm-mongo"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: marcus/ibm-atm-challenge-app
    container_name: "atm-app"
    ports:
      - 8080:8080
    links:
      - mongodb
